# Generated by Django 5.0.6 on 2024-12-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='landos',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
