# Generated by Django 5.0.2 on 2024-12-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post_landos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='landos',
        ),
        migrations.AddField(
            model_name='post',
            name='landos22',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
