# Generated by Django 5.0.2 on 2024-12-22 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_post_landos_post_landos22'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='landos22',
            new_name='landos',
        ),
    ]
